config/routes.rb
Rails.application.routes.draw do
    root 'invoices#index'

   resources :invoices, only: [:index, :show]
    get 'invoices/index'
    get 'invoices/show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    has_many :invoice_items, dependent: :destroy

    STATUS_CLASS = {
        :draft => "badge badge-secondary",
        :sent => "badge badge-primary",
        :paid => "badge badge-success"
    }

    def subtotal
        self.invoice_items.map { |item| item.qty * item.price }.sum
    end

    def discount_calculated
        subtotal * (self.discount / 100.0)
    end

    def vat_calculated
        (subtotal - discount_calculated) * (self.vat / 100.0)
    end

    def total
        subtotal - discount_calculated + vat_calculated
    end

    def status_class
        STATUS_CLASS[self.status.to_sym]
    end

end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :invoice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
require './lib/PDFNetWrappers/PDFNetC/Lib/PDFNetRuby'
include PDFNetRuby
require './lib/PDFNetWrappers/Samples/LicenseKey/RUBY/LicenseKey'

class InvoicesController < ApplicationController

  def convertToCentString (f)
   return (((((f)*100).to_i).to_d)/100).to_s
  end
  def index
      @invoices = scope
  end

  def show
      @invoice = scope.find(params[:id])
      invMod = Object.new
      invMod.instance_variable_set(:@id, @invoice.id.to_s)
      invMod.instance_variable_set(:@subtotal, convertToCentString(@invoice.subtotal))
      invMod.instance_variable_set(:@discount_calculated, convertToCentString(@invoice.discount_calculated))
      invMod.instance_variable_set(:@vat_calculated, convertToCentString(@invoice.vat_calculated))
      invMod.instance_variable_set(:@total, convertToCentString(@invoice.total));
      invMod.instance_variable_set(:@from_full_name, @invoice.from_full_name);
      invMod.instance_variable_set(:@from_address, @invoice.from_address);
      invMod.instance_variable_set(:@from_email, @invoice.from_email);
      invMod.instance_variable_set(:@from_phone, @invoice.from_phone);
      invMod.instance_variable_set(:@to_full_name, @invoice.to_full_name);
      invMod.instance_variable_set(:@to_address, @invoice.to_address);
      invMod.instance_variable_set(:@to_email, @invoice.to_email);
      invMod.instance_variable_set(:@to_phone, @invoice.to_phone);
      invMod.instance_variable_set(:@created_at, (@invoice.created_at).strftime('%d/%m/%Y'));
      invMod.instance_variable_set(:@due_at, (@invoice.created_at + 1.month).strftime('%d/%m/%Y'));
      invMod.instance_variable_set(:@discount, @invoice.discount);
      invMod.instance_variable_set(:@vat, @invoice.vat);
      invMod.instance_variable_set(:@status, @invoice.status);

      # add the rows
      rows = []
      @invoice.invoice_items.each do |key, item|
        row= Object.new
        row.instance_variable_set(:@name, key.name);
        row.instance_variable_set(:@description, key.description);
        row.instance_variable_set(:@price, key.price);
        row.instance_variable_set(:@qty, key.qty.to_s);
        row.instance_variable_set(:@total, key.qty.to_d * key.price.to_d);
        rows << row
      end

      invMod.instance_variable_set(:@rows, rows)
      json = invMod.to_json

      respond_to do |format|
        format.html 
        format.pdf do
          PDFNet.Initialize(PDFTronLicense.Key)
          $inputPath = "./app/assets/files/"
          inputFilename = "template.docx"

          # Create a TemplateDocument object from an input office file.
          inputFile = $inputPath + inputFilename
          templateDoc = Convert.CreateOfficeTemplate(inputFile, nil)

          # Fill the template with data from a JSON string, producing a PDF document.
          pdfdoc = templateDoc.FillTemplateJson(json)
          buffer = pdfdoc.Save(SDFDoc::E_linearized)

          send_data(buffer, filename: 'my-awesome-pdf.pdf', type: 'application/pdf', :disposition=>'inline')
          PDFNet.Terminate()
        end
      end   
  end

  private
      def scope
          ::Invoice.all.includes(:invoice_items)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">From</th>
      <th scope="col">To</th>
      <th scope="col">Status</th>
      <th scope="col">Discount (%)</th>
      <th scope="col">VAT (%)</th>
      <th scope="col">TOTAL</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <th scope="row"><%= invoice.created_at.strftime('%d/%m/%Y') %></th>
        <td><%= invoice.from_full_name %></td>
        <td><%= invoice.to_full_name %></td>
        <td><span class="<%= invoice.status_class %>"><%= invoice.status %></span></td>
        <td><%= invoice.discount %></td>
        <td><%= invoice.vat %></td>
        <td><%= number_to_currency(invoice.total) %></td>
        <td><%= link_to 'View', invoice_path(invoice) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoices/show.html.erb
<div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
          <tr class="top">
            <td colspan="4">
              <table>
                <tr>
                  <td class="title">
                   <%= image_tag ('company_logo.png') %>
                  </td>

                  <td>
                    Invoice #: <b><%= @invoice.id %></b>
                    <br>
                    Created: <b><%= @invoice.created_at.strftime('%d/%m/%Y') %></b>
                    <br>
                    Due: <b><%= (@invoice.created_at + 1.month).strftime('%d/%m/%Y') %></b>
                    <br>
                    Status: <span class="<%= @invoice.status_class %>"><%= @invoice.status %></span>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr class="information">
            <td colspan="4">
              <table>
                <tr>
                  <td>
                    <b><%= @invoice.from_full_name %></b><br>
                    <%= @invoice.from_address %><br>
                    <i class="far fa-envelope"></i> <%= @invoice.from_email %><br>
                    <i class="fas fa-phone"></i> <%= @invoice.from_phone %>
                  </td>

                  <td>
                    <b><%= @invoice.to_full_name %></b><br>
                    <%= @invoice.to_address %><br>
                    <i class="far fa-envelope"></i> <%= @invoice.to_email %><br>
                    <i class="fas fa-phone"></i> <%= @invoice.to_phone %>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr class="heading">
            <td>Payment Method</td>
            <td colspan="2"></td>
            <td class="right">Cache</td>
          </tr>

          <tr class="details">
            <td>Delivery Method</td>
            <td colspan="2"></td>
            <td class="right">1000</td>
          </tr>

          <tr class="heading">
            <td>Item</td>
            <td class="right">Price</td>
            <td class="right">Qty</td>
            <td>Total</td>
          </tr>

          <% @invoice.invoice_items.each do |invoice_item| %>
            <tr class="item">
                <td>
                    <%= invoice_item.name %><br>
                    <small><%= invoice_item.description %></small>
                </td>

                <td class="right">
                    <%= number_to_currency(invoice_item.price) %>
                </td>

                <td class="right">
                    x <%= invoice_item.qty %>
                </td>

                <td>
                    <%= number_to_currency(invoice_item.price * invoice_item.qty) %>
                </td>
            </tr>
          <% end %>

          <tr>
            <td colspan="4"></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>Subtotal</b></td>
            <td><%= number_to_currency(@invoice.subtotal) %></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>Discount (<%= @invoice.discount %>%)</b></td>
            <td>- <%= number_to_currency(@invoice.discount_calculated) %></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>VAT (<%= @invoice.vat %>%)</b></td>
            <td>+ <%= number_to_currency(@invoice.vat_calculated) %></td>
          </tr>

          <tr class="heading">
            <td colspan="2"></td>
            <td><b>TOTAL:</b></td>
            <td>
               <b><%= number_to_currency(@invoice.total) %></b>
            </td>
          </tr>
        </table>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>PDFs - Ruby on Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/shared/header" %>
  <div class="container mt-3">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
        <h1>Rails Generate PDFs</h1>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      </ul>

      <% if action_name.to_sym == :show %>
        <%= link_to 'Back', root_path, class: "btn btn-outline-secondary mx-2" %>
        <%= link_to 'DOWNLOAD PDF', invoice_path(::Invoice.find(params[:id]), format: :pdf), class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>

  </div>
</nav>